// In-memory seed data for FM_MODE=mock, shaped exactly like the real Schedule /
// Intake_System / Clients tables so the mock and OData adapters return identical
// shapes to the routes layer. Dates are generated relative to "today" each time
// the server starts, so the demo always looks current.

function pad(n) {
  return String(n).padStart(2, '0');
}

function fmtDate(d) {
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
}

function addDays(base, days) {
  const d = new Date(base);
  d.setDate(d.getDate() + days);
  return d;
}

const today = new Date();
today.setHours(0, 0, 0, 0);
// Sunday of the current week, to match the Sun-Sat week grid in the UI.
const weekStart = addDays(today, -today.getDay());

function d(offsetFromWeekStart) {
  return fmtDate(addDays(weekStart, offsetFromWeekStart));
}

const clients = [
  {
    ClientID: 'C1001',
    'First Name': 'Craig',
    'Last Name': 'Davis',
    PhoneNumber: '513-235-5567',
    'Email Address': 'craig.davis@example.com',
    'Street Address': '9463 Tebbs Ct.',
    City: 'Harrison',
    State: 'OH',
    Zip: '45030',
  },
  {
    ClientID: 'C1002',
    'First Name': 'Maria',
    'Last Name': 'Chen',
    PhoneNumber: '513-555-0142',
    'Email Address': 'maria.chen@example.com',
    'Street Address': '212 Oakview Dr.',
    City: 'Cincinnati',
    State: 'OH',
    Zip: '45208',
  },
  {
    ClientID: 'C1003',
    'First Name': 'George',
    'Last Name': 'Ibarra',
    PhoneNumber: '513-555-0199',
    'Email Address': 'george.ibarra@example.com',
    'Street Address': '77 Ridge Rd.',
    City: 'Milford',
    State: 'OH',
    Zip: '45150',
  },
];

const intakeSystem = [
  { 'Intake ID': 'I2001', Pets_Name: 'Farley', 'CS ID': 'C1001' },
  { 'Intake ID': 'I2002', Pets_Name: 'Molly', 'CS ID': 'C1002' },
  { 'Intake ID': 'I2003', Pets_Name: 'Rusty', 'CS ID': 'C1003' },
];

// Every field mirrors the live Schedule table exactly: kp_ScheduleID, Event_Start_Date,
// Event_Start_Time, Event_End_Date, Event_End_Time, Event_Description, Event_Notes,
// Address, City, State, Zip, Phone, Resources, All_Day_Event, kf_Intake_ID.
const appointments = [
  {
    kp_ScheduleID: 'cal-100001',
    Event_Start_Date: d(4),
    Event_Start_Time: '09:00',
    Event_End_Date: d(4),
    Event_End_Time: '09:45',
    Event_Description: 'Home euthanasia - Farley',
    Event_Notes: 'Small dog, 115-120 lbs. Family very attached, allow extra time.',
    Address: '9463 Tebbs Ct.',
    City: 'Harrison',
    State: 'OH',
    Zip: '45030',
    Phone: '513-235-5567',
    Resources: 'Vet',
    All_Day_Event: false,
    kf_Intake_ID: 'I2001',
  },
  {
    kp_ScheduleID: 'cal-100002',
    Event_Start_Date: d(4),
    Event_Start_Time: '11:00',
    Event_End_Date: d(4),
    Event_End_Time: '12:00',
    Event_Description: 'Home visit - Molly',
    Event_Notes: '',
    Address: '212 Oakview Dr.',
    City: 'Cincinnati',
    State: 'OH',
    Zip: '45208',
    Phone: '513-555-0142',
    Resources: 'Vet Tech',
    All_Day_Event: false,
    kf_Intake_ID: 'I2002',
  },
  {
    kp_ScheduleID: 'cal-100003',
    Event_Start_Date: d(5),
    Event_Start_Time: '10:00',
    Event_End_Date: d(5),
    Event_End_Time: '11:00',
    Event_Description: 'Chapel viewing',
    Event_Notes: '',
    Address: '100 Main St.',
    City: 'Loveland',
    State: 'OH',
    Zip: '45140',
    Phone: '',
    Resources: 'Chapel',
    All_Day_Event: false,
    kf_Intake_ID: null,
  },
  {
    kp_ScheduleID: 'cal-100004',
    Event_Start_Date: d(6),
    Event_Start_Time: '13:00',
    Event_End_Date: d(6),
    Event_End_Time: '14:00',
    Event_Description: 'Follow-up call - Tammy',
    Event_Notes: '',
    Address: '',
    City: '',
    State: '',
    Zip: '',
    Phone: '513-555-0177',
    Resources: 'Tammy',
    All_Day_Event: false,
    kf_Intake_ID: null,
  },
  {
    kp_ScheduleID: 'cal-100005',
    Event_Start_Date: d(3),
    Event_Start_Time: '08:00',
    Event_End_Date: d(3),
    Event_End_Time: '09:00',
    Event_Description: 'Staff meeting',
    Event_Notes: '',
    Address: '',
    City: '',
    State: '',
    Zip: '',
    Phone: '',
    Resources: 'Office',
    All_Day_Event: false,
    kf_Intake_ID: null,
  },
  {
    kp_ScheduleID: 'cal-100006',
    Event_Start_Date: d(5),
    Event_Start_Time: '14:00',
    Event_End_Date: d(5),
    Event_End_Time: '15:00',
    Event_Description: 'New intake paperwork',
    Event_Notes: '',
    Address: '',
    City: '',
    State: '',
    Zip: '',
    Phone: '',
    Resources: 'Intake',
    All_Day_Event: false,
    kf_Intake_ID: null,
  },
  {
    kp_ScheduleID: 'cal-100007',
    Event_Start_Date: d(6),
    Event_Start_Time: '10:00',
    Event_End_Date: d(6),
    Event_End_Time: '10:45',
    Event_Description: 'Grief support consult - Rusty',
    Event_Notes: 'Second consult this month.',
    Address: '77 Ridge Rd.',
    City: 'Milford',
    State: 'OH',
    Zip: '45150',
    Phone: '513-555-0199',
    Resources: 'Social Worker',
    All_Day_Event: false,
    kf_Intake_ID: 'I2003',
  },
  {
    kp_ScheduleID: 'cal-100008',
    Event_Start_Date: d(5),
    Event_Start_Time: '07:00',
    Event_End_Date: d(5),
    Event_End_Time: '08:00',
    Event_Description: 'Transport pickup',
    Event_Notes: '',
    Address: '',
    City: '',
    State: '',
    Zip: '',
    Phone: '',
    Resources: 'Transporter',
    All_Day_Event: false,
    kf_Intake_ID: null,
  },
  {
    kp_ScheduleID: 'cal-100009',
    Event_Start_Date: d(0),
    Event_Start_Time: '15:00',
    Event_End_Date: d(0),
    Event_End_Time: '15:30',
    Event_Description: 'Phone check-in',
    Event_Notes: '',
    Address: '',
    City: '',
    State: '',
    Zip: '',
    Phone: '',
    Resources: 'none',
    All_Day_Event: false,
    kf_Intake_ID: null,
  },
  {
    kp_ScheduleID: 'cal-100010',
    Event_Start_Date: d(4),
    Event_Start_Time: null,
    Event_End_Date: d(4),
    Event_End_Time: null,
    Event_Description: 'PHONE HUG AT ANYTIME - confirm time',
    Event_Notes: 'Family requested a call before we lock the time.',
    Address: '9463 Tebbs Ct.',
    City: 'Harrison',
    State: 'OH',
    Zip: '45030',
    Phone: '513-235-5567',
    Resources: 'Vet',
    All_Day_Event: true,
    kf_Intake_ID: 'I2001',
  },
  {
    kp_ScheduleID: 'cal-100011',
    Event_Start_Date: d(5),
    Event_Start_Time: null,
    Event_End_Date: d(5),
    Event_End_Time: null,
    Event_Description: 'Chapel time TBD',
    Event_Notes: '',
    Address: '',
    City: '',
    State: '',
    Zip: '',
    Phone: '',
    Resources: 'Chapel',
    All_Day_Event: true,
    kf_Intake_ID: null,
  },
  {
    kp_ScheduleID: 'cal-100012',
    Event_Start_Date: d(2),
    Event_Start_Time: null,
    Event_End_Date: d(4),
    Event_End_Time: null,
    Event_Description: 'Vet Tech training conference',
    Event_Notes: 'Out of office all three days.',
    Address: '',
    City: '',
    State: '',
    Zip: '',
    Phone: '',
    Resources: 'Vet Tech',
    All_Day_Event: true,
    kf_Intake_ID: null,
  },
  {
    kp_ScheduleID: 'cal-100013',
    Event_Start_Date: d(1),
    Event_Start_Time: '14:00',
    Event_End_Date: d(2),
    Event_End_Time: '12:00',
    Event_Description: 'Extended in-home hospice stay',
    Event_Notes: 'Spans overnight; coordinate with on-call vet.',
    Address: '',
    City: '',
    State: '',
    Zip: '',
    Phone: '',
    Resources: 'Office',
    All_Day_Event: false,
    kf_Intake_ID: null,
  },
  {
    kp_ScheduleID: 'cal-100014',
    Event_Start_Date: null,
    Event_Start_Time: null,
    Event_End_Date: null,
    Event_End_Time: null,
    Event_Description: 'New inquiry - awaiting callback',
    Event_Notes: 'Left voicemail 2x.',
    Address: '',
    City: '',
    State: '',
    Zip: '',
    Phone: '513-555-0210',
    Resources: 'Vet',
    All_Day_Event: true,
    kf_Intake_ID: null,
  },
  {
    kp_ScheduleID: 'cal-100015',
    Event_Start_Date: null,
    Event_Start_Time: null,
    Event_End_Date: null,
    Event_End_Time: null,
    Event_Description: 'Family requested consult, date TBD',
    Event_Notes: '',
    Address: '',
    City: '',
    State: '',
    Zip: '',
    Phone: '',
    Resources: 'Social Worker',
    All_Day_Event: true,
    kf_Intake_ID: 'I2003',
  },
  {
    kp_ScheduleID: 'cal-100016',
    Event_Start_Date: d(7),
    Event_Start_Time: '09:00',
    Event_End_Date: d(7),
    Event_End_Time: '10:00',
    Event_Description: 'Standalone transport - no client record',
    Event_Notes: 'Booked directly, not linked to an intake.',
    Address: '55 River Rd.',
    City: 'Batavia',
    State: 'OH',
    Zip: '45103',
    Phone: '513-555-0333',
    Resources: 'Transporter',
    All_Day_Event: false,
    kf_Intake_ID: null,
  },
  {
    kp_ScheduleID: 'cal-100017',
    Event_Start_Date: d(8),
    Event_Start_Time: '09:00',
    Event_End_Date: d(8),
    Event_End_Time: '10:00',
    Event_Description: 'Community outreach event',
    Event_Notes: '',
    Address: '',
    City: '',
    State: '',
    Zip: '',
    Phone: '',
    Resources: 'Marketing',
    All_Day_Event: false,
    kf_Intake_ID: null,
  },
];

let nextId = appointments.length + 1;
function generateId() {
  return `cal-${100000 + nextId++}`;
}

module.exports = { appointments, intakeSystem, clients, generateId };
